### ISSUE TITLE
Sound latency on Android

### ISSUE THREAD

**Issue by Oscar-Rodrigues** [Digitopia/01som#12] opened 2018-01-11 15:04 UTC
On Chrome for Android, sounds are triggering way after the visual feedback, so the app is not as responsive and the visual and musical parts get out of sync.

**Comment by Oscar-Rodrigues** [comment] 2018-01-11 15:06
(This happens on S1 and on a OnePlus 3t)

**Comment by nunoh** [comment] 2018-05-11 17:15
Ups.. Commit message was "possibly fixes #12" and it automatically closed the issue. 

Awaiting for @Oscar-Rodrigues to validate if this if actually fixed or not. Fyi, it is using `Tone.Draw` already and I think the delay that might be perceived is because of the sample itself. I also tried removing the silence in the .mp3 files at the beginning. We had a intro silence of about 0.06 seconds which is roughly a 16th note at 120 bpm. That's still something..

**Comment by nunoh** [comment] 2020-03-03 12:14
Closing as cannot reproduce

**Closed as completed by nunoh** 2020-03-03 12:14 UTC
Labels: bug
